# Generated by Django 3.2.6 on 2021-08-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('article', models.CharField(blank=True, max_length=16, null=True, verbose_name='Арт.')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Количество')),
            ],
        ),
    ]
